### ISSUE TITLE
Convert the rpm-ostree commands into a single one

### ISSUE THREAD

**Issue by boredsquirrel** [john-ghatas/fedora-simple-startup#4]
This is great for speed

`rpm-ostree update --install x`

I dont know if it works with `--override remove x --install y` too

Also fedora people said you always have to update when installing packages to avoid conflicts

**Comment by john-ghatas** [comment]
You could do that but I have not seen any issues with installing packages, you will update anyway 5 minutes before installing at most. I will take a look at the faster install method you mentioned later.

**Comment by john-ghatas** [comment]
Could possibly make use of the live patching capabilities of rpm-ostree but to keep a pinned install in case something borks it would be wise to keep the current deployment as is.

**Comment by john-ghatas** [comment]
Compared both methods of installing on a fresh Kinoite install in a VM

Run 1

**Normal install** 4 Minutes 18 seconds

**Install with update** 3 MInutes 5 seconds

Run 2

**Normal install** 3 Minutes and 12 seconds

**Install with update** 2 Minutes 51 Seconds

Seems like the gains are marginal here.


As for the installing of all packages in one go the split is there for the reason mentioned in my first comment, do you agree on closing this issue?

EDIT: The packages are installed after the reboot for the sole reason that rpmfusion needs to be active, I see no reason to live patch this.

**Comment by boredsquirrel** [comment]
ok if you want two deployments that makes sense. 

Interesting so if you add the repo as a rpm you need to reboot, I think if you add the repo file you dont, but this may have disadvantages.

So the runs where you updated where faster? thats crazy! Then we should always use that.

Thanks for your research

**Comment by john-ghatas** [comment]
Marginally faster, it doesn't matter much in the grand scheme of things. Also there is a deviation in the install times if you look closely +- 20 seconds faster or slower with the same method. So it isn't that much faster  (the first run took longer because rpm-ostree needed to update the metadata/sources on the first install try hence why I did 2 runs, not 1).

**Comment by boredsquirrel** [comment]
But Fedora devs told me after I had an issue with many packages just not being able to be found that I have to update --install instead of directly installing.

Weirdly after updating and rebooting I  could install them, so this makes sense. So running update --install will avoid random erros in your setup.

**Comment by john-ghatas** [comment]
May I ask what package that was at the time? I tested this install on 3 machines and I did not encounter any issues

**Comment by boredsquirrel** [comment]
unrar, waydroid, and more. tlp was the only thing installing

I also didnt experience that on my main machine, dont know

**Comment by john-ghatas** [comment]
Thanks im testing the mentioned packages my VM

**Comment by john-ghatas** [comment]
All mentioned packages install fine with the normal install command, could have been an invalidated cache/metadata or corrupted cache at the time of installing. To make sure we can close the issue: you did not encounter this with the silverblue script provided in this repo? An update is being done before diong anything so this will probably not be an issue :)
